/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Thumbnail = {
  _type: "thumbnail";
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Meta = {
  _type: "meta";
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: Array<string>;
  tags?: Array<string>;
};

export type Game = {
  _id: string;
  _type: "game";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  is_active?: boolean;
  title?: string;
  game_slug?: Slug;
  game_url?: string;
  description?: string;
  faq?: Array<
    {
      _key: string;
    } & Faq
  >;
  genre?: string;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "gameCategory";
  };
  is_external?: boolean;
  seo?: Meta;
  rating?: number;
  total_likes_in_percentage?: number;
  total_play_count?: number;
  developer_name?: string;
  badge?: string;
  thumbnail?: Thumbnail;
  video_thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type GameCategory = {
  _id: string;
  _type: "gameCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  is_active?: boolean;
  title?: string;
  description?: string;
  thumbnail?: Thumbnail;
  slug?: Slug;
  seo?: Meta;
  related_categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "gameCategory";
  }>;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _type: "faq";
  question?: string;
  answer?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Thumbnail
  | Meta
  | Game
  | Slug
  | GameCategory
  | SanityImageCrop
  | SanityImageHotspot
  | Faq
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: recentGamesQuery
// Query: *[_type == 'game' && is_active == true && !(_id in path('drafts.**'))] | order(created_at){        _id,        title,        description,        game_slug,        badge,        thumbnail{          ...thumbnail{          asset ->        }        },      }[0...5]
export type RecentGamesQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  game_slug: Slug | null;
  badge: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
}>;
// Variable: popularGamesQuery
// Query: *[_type == "game" && is_active == true && !(_id in path('drafts.**'))]| order(rating desc){        _id,        title,        description,        game_slug,        badge,        thumbnail{          ...thumbnail{          asset ->        }        },      }[0...5]
export type PopularGamesQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  game_slug: Slug | null;
  badge: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
}>;
// Variable: gamesCategoryQuery
// Query: *[_type == "gameCategory" && is_active == true && !(_id in path('drafts.**'))] | order(orderRank)[0...4]{      _id,      title,      description,      thumbnail{        ...thumbnail{          asset ->        }      },      slug,      seo      }
export type GamesCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
  slug: Slug | null;
  seo: Meta | null;
}>;
// Variable: gamesQuery
// Query: *[_type == "game" && is_active == true && !(_id in path('drafts.**'))]| order(orderRank){      _id,      title,      game_slug,      badge,      thumbnail{        ...thumbnail{          asset ->        }      },      }[0...120]
export type GamesQueryResult = Array<{
  _id: string;
  title: string | null;
  game_slug: Slug | null;
  badge: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
}>;
// Variable: gamesByCategoryQuery
// Query: *[_type == "game" && is_active == true && !(_id in path('drafts.**')) && category == $gameCategory ]| order(orderRank){      _id,      title,      game_slug,      badge,      thumbnail{        ...thumbnail{          asset ->        }      },      }[0...120]
export type GamesByCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  game_slug: Slug | null;
  badge: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
}>;
// Variable: gameBySlugQuery
// Query: *[_type == "game" && is_active == true && game_slug.current == $gameSlug && !(_id in path('drafts.**'))][0]{        _id,        title,        description,        game_slug,        game_url,        rating,        total_likes_in_percentage,        total_play_count,        faq,        developer_name,        genre,        category -> {          _id,          title,          slug,          thumbnail{            ...thumbnail{          asset ->        }          },          related_categories[]->{            ...,            thumbnail{              ...thumbnail{          asset ->        }            },          },        },        badge,        thumbnail{          ...thumbnail{          asset ->        }        },        is_active,        is_external,        seo,        "related_games":*[_type == "game" && is_active == true && !(_id in path('drafts.**')) && category._ref in (*[_type == "game" && is_active == true && game_slug.current == $gameSlug && !(_id in path('drafts.*'))][0]{          "related_categories" : (category->{    "ids" : related_categories[] -> {_id}["_id"]           })}["related_categories"]["ids"])]| order(orderRank){            _id,            title,            description,            game_slug,            badge,            thumbnail{              ...thumbnail{          asset ->        }            },          },      }
export type GameBySlugQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  game_slug: Slug | null;
  game_url: string | null;
  rating: number | null;
  total_likes_in_percentage: number | null;
  total_play_count: number | null;
  faq: Array<
    {
      _key: string;
    } & Faq
  > | null;
  developer_name: string | null;
  genre: string | null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    thumbnail:
      | {}
      | {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        }
      | null;
    related_categories: Array<{
      _id: string;
      _type: "gameCategory";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      is_active?: boolean;
      title?: string;
      description?: string;
      thumbnail:
        | {}
        | {
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
          }
        | null;
      slug?: Slug;
      seo?: Meta;
      related_categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "gameCategory";
      }>;
      orderRank?: string;
    }> | null;
  } | null;
  badge: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
  is_active: boolean | null;
  is_external: boolean | null;
  seo: Meta | null;
  related_games: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    game_slug: Slug | null;
    badge: string | null;
    thumbnail:
      | {}
      | {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        }
      | null;
  }>;
} | null;
// Variable: categoryBySlugQuery
// Query: *[_type == "gameCategory" && is_active == true && slug.current == $categorySlug && !(_id in path('drafts.**'))][0]{        _id,        title,        description,        thumbnail{          ...thumbnail{          asset ->        }        },        slug,        seo,        "related_categories":(related_categories[]->{          _id,        title,        thumbnail{          ...thumbnail{          asset ->        }        },        slug,        seo,        is_active        })[is_active == true],        "related_games": *[_type == "game" && is_active == true && !(_id in path('drafts.**'))] | order(orderRank)[0...50]{          _id,          title,          description,          game_slug,          badge,          thumbnail{            ...thumbnail{          asset ->        }          }        }      }
export type CategoryBySlugQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  thumbnail:
    | {}
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      }
    | null;
  slug: Slug | null;
  seo: Meta | null;
  related_categories: Array<{
    _id: string;
    title: string | null;
    thumbnail:
      | {}
      | {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        }
      | null;
    slug: Slug | null;
    seo: Meta | null;
    is_active: boolean | null;
  }> | null;
  related_games: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    game_slug: Slug | null;
    badge: string | null;
    thumbnail:
      | {}
      | {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
        }
      | null;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'game' && is_active == true && !(_id in path('drafts.**'))] | order(created_at){\n        _id,\n        title,\n        description,\n        game_slug,\n        badge,\n        thumbnail{\n          ...thumbnail{\n          asset ->\n        }\n        },\n      }[0...5]": RecentGamesQueryResult;
    "*[_type == \"game\" && is_active == true && !(_id in path('drafts.**'))]| order(rating desc){\n        _id,\n        title,\n        description,\n        game_slug,\n        badge,\n        thumbnail{\n          ...thumbnail{\n          asset ->\n        }\n        },\n      }[0...5]": PopularGamesQueryResult;
    "*[_type == \"gameCategory\" && is_active == true && !(_id in path('drafts.**'))] | order(orderRank)[0...4]{\n      _id,\n      title,\n      description,\n      thumbnail{\n        ...thumbnail{\n          asset ->\n        }\n      },\n      slug,\n      seo\n      }": GamesCategoryQueryResult;
    "*[_type == \"game\" && is_active == true && !(_id in path('drafts.**'))]| order(orderRank){\n      _id,\n      title,\n      game_slug,\n      badge,\n      thumbnail{\n        ...thumbnail{\n          asset ->\n        }\n      },\n      }[0...120]": GamesQueryResult;
    "*[_type == \"game\" && is_active == true && !(_id in path('drafts.**')) && category == $gameCategory ]| order(orderRank){\n      _id,\n      title,\n      game_slug,\n      badge,\n      thumbnail{\n        ...thumbnail{\n          asset ->\n        }\n      },\n      }[0...120]": GamesByCategoryQueryResult;
    '*[_type == "game" && is_active == true && game_slug.current == $gameSlug && !(_id in path(\'drafts.**\'))][0]{\n        _id,\n        title,\n        description,\n        game_slug,\n        game_url,\n        rating,\n        total_likes_in_percentage,\n        total_play_count,\n        faq,\n        developer_name,\n        genre,\n        category -> {\n          _id,\n          title,\n          slug,\n          thumbnail{\n            ...thumbnail{\n          asset ->\n        }\n          },\n          related_categories[]->{\n            ...,\n            thumbnail{\n              ...thumbnail{\n          asset ->\n        }\n            },\n          },\n        },\n        badge,\n        thumbnail{\n          ...thumbnail{\n          asset ->\n        }\n        },\n        is_active,\n        is_external,\n        seo,\n        "related_games":*[_type == "game" && is_active == true && !(_id in path(\'drafts.**\')) && category._ref in (*[_type == "game" && is_active == true && game_slug.current == $gameSlug && !(_id in path(\'drafts.*\'))][0]{\n          "related_categories" : (category->{    "ids" : related_categories[] -> {_id}["_id"]\n           })}["related_categories"]["ids"])]| order(orderRank){\n            _id,\n            title,\n            description,\n            game_slug,\n            badge,\n            thumbnail{\n              ...thumbnail{\n          asset ->\n        }\n            },\n          },\n      }': GameBySlugQueryResult;
    '*[_type == "gameCategory" && is_active == true && slug.current == $categorySlug && !(_id in path(\'drafts.**\'))][0]{\n        _id,\n        title,\n        description,\n        thumbnail{\n          ...thumbnail{\n          asset ->\n        }\n        },\n        slug,\n        seo,\n        "related_categories":(related_categories[]->{\n          _id,\n        title,\n        thumbnail{\n          ...thumbnail{\n          asset ->\n        }\n        },\n        slug,\n        seo,\n        is_active\n        })[is_active == true],\n        "related_games": *[_type == "game" && is_active == true && !(_id in path(\'drafts.**\'))] | order(orderRank)[0...50]{\n          _id,\n          title,\n          description,\n          game_slug,\n          badge,\n          thumbnail{\n            ...thumbnail{\n          asset ->\n        }\n          }\n        }\n      }': CategoryBySlugQueryResult;
  }
}
